### ISSUE TITLE
Does not work on real scenes

### ISSUE THREAD

**Issue by siliconvalleypilot** [naruya/VaxNeRF#5]
I tried the visual hull code on a few real scenes (from LLFF and Tanks&Temple datasets), all scenes return wrong visual hulls (because of ground plane and background noise). Does this approach only work on synthetic data?

**Comment by naruya** [comment]
Oh yes, our approarch can be used for inward facing scenes only...

**Comment by naruya** [comment]
but maybe visual hull would work if the backgrounds were removed from the images. (Note that the ndc coordinate (spherify==False) is not supported.)

**Comment by Learningm** [comment]
I tried my inward facing real data, the visual hull code not work either.
I run nerf-studio to get the transforms.json and make a rgba dataset using some segmentation method to get the mask. And I rewrote the dataset part, use transform_matrix in the transforms.json. 
But the result is not good, could you give me some advises?

**Comment by naruya** [comment]
@Learningm  Is visual hull working on the original nerf synthesis dataset? Sorry but that's all I can support. I would recommend to debug it by visualizing the camera rays.
