### ISSUE TITLE
question of digitize function

### ISSUE THREAD

**Issue by zhangjian94cn** [naruya/VaxNeRF#8]
Hello, I cannot understand this function clearly. I know that digitize is used to convert p's location to voxel index. But why do you add rsize to p ?`p+rsize`.

Rsize is half value of far-near, which will change p's location. Then, you limit voxelized p to [0, vsize-1], but in real world coordinator(e.g. llff), voxelized p in range  [0, vsize-1] may not contain object.

Or rsize here is just an empirical offset？

```python
@partial(jit, static_argnums=(1,2,))
def digitize(p, rsize, vsize):
    p = jnp.round((p+rsize) * (vsize/(rsize*2)))
    return jnp.clip(p.astype(jnp.uint16), 0, vsize-1)\
```

**Comment by naruya** [comment]
Sorry, I don't remember much about my these codes, but I think the position xyz of `p` takes `-r ~ r`, so I added `r` so that it goes `0 ~ 2r` (or something like that). And..., VaxNeRF only supports inward facing datasets and cannot be used with llff, etc. 😱

**Comment by zhangjian94cn** [comment]
Thank you! I got it.
