### ISSUE TITLE
using the concept of voxel acceleration for Deblr-NeRF

### ISSUE THREAD

**Issue by addy1997** [naruya/VaxNeRF#9]
Hi @naruya,

This is amazing work. I  am working on deblurring NeRF using blurry input scenes. Is it possible to use the concept of VaxNeRF in this[ nerf model](https://github.com/limacv/Deblur-NeRF)?

Thanks

**Comment by naruya** [comment]
Thanks for finding our research!

First, a sad announcement: vaxnerf is not available for forward-facing scene, and, in my experience, implementing vaxnerf with pytorch is not as fast as implementing it with Jax.

I think these commits are helpful for vaxing NeRF with pytorch.
https://github.com/naruya/torchnerf/compare/30c3225...f2ddadb

thanks!
